### ISSUE TITLE
feat: Responsive alerts

### ISSUE THREAD

**Issue by Vikram-Hegde** [Vikram-Hegde/alerts-n-toasts#2]
Currently alerts are designed only for desktop and don't look acceptable on smaller devices.

**Comment by Muz4mmil** [comment]
Hi @Vikram-Hegde ,
I checked the website and it looks like just the alert width issue on mobile devices.
I have a good hold on SCSS, Assign me this issue under hacktoberfest and i can fix it.

**Comment by Vikram-Hegde** [comment]
@Muz4mmil yup that's the issue. Just make sure you're doing a PR to a new branch named "responsive alerts" rather than the main branch, Assigning you this task

**Comment by Muz4mmil** [comment]
> @Muz4mmil yup that's the issue. Just make sure you're doing a PR to a new branch named "responsive alerts" rather than the main branch, Assigning you this task

Done, Kindly check and merge the PR

**Comment by Vikram-Hegde** [comment]
@Muz4mmil Thanks for your contribution 😄
